<?php

namespace HeticBundle\Repository;

/**
 * EtudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudRepository extends \Doctrine\ORM\EntityRepository
{
}
