<?php

namespace HeticBundle\Repository;

/**
 * EtudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllDateOfBirth()
    {
//        $repository = $this
//            ->getDoctrine()
//            ->getManager()
//            ->getRepository('HeticBundle:Etud');
//
//        $students = $repository->findBy(
//            array('date_of_birth' => 'desc')
//        );

//        foreach ($students as $student) {
//            echo $student->getContent();
//        }

    }
}
